import { Navigation } from '@/components/Navigation'
import { Roboto } from 'next/font/google'

import './globals.css'

export const metadata = {
  title: 'Ecommerce-next13',
  description: 'Generated by create next app',
}
const roboto = Roboto({ subsets: ['latin'],weight: '400'})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
